name: WallsReloaded
version: 1.1.4
main: com.thundergemios10.walls.Walls
authors: [Double0negative, ThunderGemios10]
description: Fully Automated Walls Plugin!

commands:
    walls:
        description: Walls Command
        usage: /w <command> <args>
        aliases: [w, walsl, wl]
