name: Walls
version: SG Build 0.5.8.42 Walls Build #${BUILD_NUMBER}
main: org.mcsg.walls.Walls
authors: [Double0negative]
description: Fully Automated Walls Plugin!

commands:
    walls:
        description: Walls Command
        usage: /w <command> <args>
        aliases: [w, walsl, wl]

