name: Walls
version: Walls Build 0.5.8.43 Walls Build #${BUILD_NUMBER}
main: me.thundergemios10.walls.Walls
authors: [Double0negative, ThunderGemios10]
description: Fully Automated Walls Plugin!

commands:
    walls:
        description: Walls Command
        usage: /w <command> <args>
        aliases: [w, walsl, wl]

